Models/UserBrands.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BackEnd_Camping.Models
{
    [Table("UserBrands")]
    public class UserBrands : BaseModel    
    {
        [Key]
        public int UBRA_ID { get; set; }
        public required int USE_ID { get; set; }
        public required int BRA_ID { get; set; }
        [ForeignKey("BRA_ID")]
        public virtual Brand? Brand { get; set; }
        [ForeignKey("USE_ID")]
        public virtual User? User { get; set; }
    }
}

Areas/Admin/Controllers/UserBrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BackEnd_Camping.Models;
using BackEnd_Camping.Utils;
using BackEnd_Camping.Areas.Admin.DTOs.response;
namespace BackEnd_Camping.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserBrandController : Controller
    {
        private readonly CampingContext _context;

        public UserBrandController(CampingContext context)
        {
            _context = context;
        }

        // GET: Admin/UserBrand
        public async Task<IActionResult> Index()
        {
            var campingContext = _context.UserBrands.Include(u => u.Brand).Include(u => u.User);
            return View(await campingContext.ToListAsync());
        }

        // GET: Admin/UserBrand/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var userBrands = await _context.UserBrands
        .Include(ub => ub.User)
        .Include(ub => ub.Brand)
        .Where(ub => ub.USE_ID == id)
        .ToListAsync();

            if (userBrands == null || !userBrands.Any())
            {
                return NotFound();
            }

            var viewModel = new UserDetailViewModel
            {
                User = userBrands.First().User,
                Brands = userBrands.Select(ub => ub.Brand).ToList()
            };

            return View(viewModel);
        }

        // GET: Admin/UserBrand/Create
        public IActionResult Create()
        {
            ViewData["BRA_ID"] = new SelectList(_context.Brands, "BRA_ID", "Name");
            ViewData["USE_ID"] = new SelectList(_context.Users, "USE_ID", "Name");
            return View();
        }

        // POST: Admin/UserBrand/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] UserBrands userBrands)
        {
            var userInfo = HttpContext.Session.Get<AdminUser>("userInfo");
            var userName = userInfo != null ? userInfo.Username : "";
            if (ModelState.IsValid)
            {
                userBrands.CreatedBy = userName;
                userBrands.CreatedDate = DateTime.Now;
                userBrands.UpdatedDate = DateTime.Now;
                userBrands.UpdatedBy = userName;
                _context.Add(userBrands);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BRA_ID"] = new SelectList(_context.Brands, "BRA_ID", "Name", userBrands.BRA_ID);
            ViewData["USE_ID"] = new SelectList(_context.Users, "USE_ID", "Name", userBrands.USE_ID);
            return View(userBrands);
        }

        // GET: Admin/UserBrand/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userBrand = _context.UserBrands
        .Include(ub => ub.Brand)
        .Include(ub => ub.User)
        .FirstOrDefault(ub => ub.UBRA_ID == id);
            if (userBrand == null)
            {
                return NotFound();
            }
            ViewData["BRA_ID"] = new SelectList(_context.Brands, "BRA_ID", "Name", userBrand.BRA_ID);
            ViewData["USE_ID"] = new SelectList(_context.Users, "USE_ID", "Name", userBrand.USE_ID);
            return View(userBrand);
        }

        // POST: Admin/UserBrand/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [FromForm] UserBrands userBrands)
        {
            if (id != userBrands.UBRA_ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var userInfo = HttpContext.Session.Get<AdminUser>("userInfo");
                var userName = userInfo != null ? userInfo.Username : "";
                try
                {
                    userBrands.UpdatedDate = DateTime.Now;
                    userBrands.UpdatedBy = userName;
                    _context.Update(userBrands);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserBrandsExists(userBrands.UBRA_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BRA_ID"] = new SelectList(_context.Brands, "BRA_ID", "Name", userBrands.BRA_ID);
            ViewData["USE_ID"] = new SelectList(_context.Users, "USE_ID", "Name", userBrands.USE_ID);
            return View(userBrands);
        }

        // GET: Admin/UserBrand/Delete/5

        // POST: Admin/UserBrand/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userBrands = await _context.UserBrands.FindAsync(id);
            if (userBrands != null)
            {
                _context.UserBrands.Remove(userBrands);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserBrandsExists(int id)
        {
            return _context.UserBrands.Any(e => e.UBRA_ID == id);
        }
    }
    
   
}

Areas/Admin/Views/UserBrand/Create.cshtml
@model BackEnd_Camping.Models.UserBrands

@{
    ViewData["Title"] = "Create";
}

<div class="container my-3">
        <form asp-action="Create">
        <div class="row">
           
            <div class="col"></div>
            <div class="col border border-2 my-auto">
                <h1 class="text-center">Add Favorites Brands</h1>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="USE_ID" class="control-label"></label>
                    <select asp-for="USE_ID" class ="form-control" asp-items="ViewBag.USE_ID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="BRA_ID" class="control-label"></label>
                    <select asp-for="BRA_ID" class ="form-control" asp-items="ViewBag.BRA_ID"></select>
                </div>
                <div class="form-group mx-2 d-flex justify-content-center align-items-center my-2">
                    <a asp-action="Index" class="text-decoration-none">
                        <button type="button" class="back-button mx-5">
                            <i class="fa-solid fa-arrow-left text-white back-svgIcon"></i>
                        </button>
                    </a>
                    <button type="submit" class="add-button mx-5">
                        <i class="fa-solid fa-plus text-white edit-svgIcon"></i>
                    </button>
                </div>
            </div>
            
            <div class="col"></div>
        </div>
        </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/UserBrand/Delete.cshtml
@model BackEnd_Camping.Models.UserBrands

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserBrands</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.BRA_ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.USE_ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UBRA_ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Admin/Views/UserBrand/Details.cshtml
@model BackEnd_Camping.Models.UserBrands

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UserBrands</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.BRA_ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.USE_ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.UBRA_ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Admin/Views/UserBrand/Edit.cshtml
@model BackEnd_Camping.Models.UserBrands

@{
    ViewData["Title"] = "Edit";
}
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
    <form asp-action="Edit">
        <div class="row">
            <div class="col"></div>
            <div class="col border border-2 my-auto">
                <h1 class="text-center">Edit Favorites Brands</h1>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="UBRA_ID" />
                <div class="form-group">
                    <label asp-for="USE_ID" class="control-label"></label>
                    <select asp-for="USE_ID" class="form-control" asp-items="ViewBag.USE_ID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="BRA_ID" class="control-label"></label>
                    <select asp-for="BRA_ID" class="form-control" asp-items="ViewBag.BRA_ID"></select>
                </div>
                <div class="form-group mx-2 d-flex justify-content-center align-items-center my-2">
                    <a asp-action="Index" class="text-decoration-none">
                        <button type="button" class="back-button mx-5">
                            <i class="fa-solid fa-arrow-left text-white back-svgIcon"></i>
                        </button>
                    </a>
                    <button type="submit" class="add-button mx-5">
                        <i class="fa-solid fa-plus text-white edit-svgIcon"></i>
                    </button>
                </div>
            </div>

            <div class="col"></div>
        </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Admin/Views/UserBrand/Index.cshtml
@model IEnumerable<BackEnd_Camping.Models.UserBrands>

@{
    ViewData["Title"] = "Index";
}
<div class="row d-flex justify-content-between my-3">
    <div class="col-4">
        <h1>Favorites Brands</h1>
    </div>
    <div class="col-1 my-auto">
        <a asp-action="create" asp-controller="UserBrand" class="text-decoration-none">
            <button class="cssbuttons-io-button">
                <span><i class="fa-solid fa-plus"></i></span>
                Add
            </button>
        </a>
    </div>
</div>
<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th style="width: 10rem;">Actions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Brand.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td class="text-center">
                    <div class="d-flex justify-content-center gap-2">
                        <a asp-action="Edit" asp-route-id="@item.UBRA_ID" class="text-decoration-none">
                        <button type="button" class="edit-button">
                                <i class="fa-solid fa-pen text-white edit-svgIcon"></i>
                        </button>
                        </a>
                        <button popovertarget="popover-delete-@item.UBRA_ID" class="trash-button">
                            <i class="fa-solid fa-trash text-white trash-svgIcon"></i>
                        </button>
                        <div id="popover-delete-@item.UBRA_ID" popover class="popover-delete rounded rounded-3 border-success-subtle border-2">
                            <div class="container" style="max-width: 400px;">
                                <div class="row">
                                    <h1>Bạn có thực sự muốn @item.Brand.Name khỏi yêu thích không?</h1>
                                </div>
                                <div class="row">
                                    <form asp-action="DeleteConfirmed" method="post" class="d-inline" onsubmit="return confirm('Bạn thực sự muốn xóa không?');">
                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="id" value="@item.UBRA_ID" />
                                        <button type="submit">
                                            <i class="fa-solid fa-trash text-white trash-svgIcon"></i>Xóa
                                        </button>
                                        <button type="button" class="close-button" onclick="location.reload()">
                                            <i class="fa-solid fa-times text-white"></i> Đóng
                                        </button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
            </td>
        </tr>
}
    </tbody>
</table>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
<script>
    function reloadPage() {
        location.reload();
    }
</script>
}